nestorzamili/sasuai-store

prisma/schema.prisma, src/app/(app)/products/brands/_components/brand-delete-dialog.tsx, src/app/(app)/products/brands/_components/brand-form-dialog.tsx, src/app/(app)/products/brands/_components/brand-primary-button.tsx, src/app/(app)/products/brands/_components/brand-table.tsx, src/app/(app)/products/brands/_components/main-content.tsx, src/app/(app)/products/brands/action.ts, src/app/(app)/products/brands/page.tsx, src/app/api/v1/brands/[id]/route.ts, src/app/api/v1/brands/route.ts, src/components/layout/data/sidebar-data.ts, src/components/ui/data-table-pagination.tsx, src/lib/api/services/brand.service.ts
Add API and page brands
Closes: #
=> Brands page

src/app/(app)/products/brands/_components/brand-table.tsx, src/app/(app)/products/categories/_components/category-table.tsx, src/app/(app)/suppliers/_components/supplier-table.tsx
=> refactor(tables): rename globalFilter to searchQuery for clarity

src/app/(app)/inventory/_components/batch-form-dialog.tsx, src/app/(app)/inventory/_components/batch-table.tsx, src/app/(app)/transactions/_components/transaction-table.tsx
refactor(transaction): remove unused imports from transaction table component
Before 
After
Closes: #
=> refactor(transaction): remove unused imports from transaction table component

src/app/(app)/products/_components/product-form/create-brand-dialog.tsx, src/app/(app)/products/_components/product-form/create-category-dialog.tsx, src/app/(app)/products/_components/product-form/create-unit-dialog.tsx, src/app/(app)/products/_components/product-form/product-form-provider.tsx
This update introduces new functions to fetch units, brands, and categories in the product form context. The CreateBrandDialog, CreateCategoryDialog, and CreateUnitDialog components have been updated to utilize these functions for fetching updated lists after creation.
Closes: #
=> feat(product-form): integrate fetch functions for units, brands, and categories

src/components/layout/table-layout.tsx
=> refactor(table): update TableBody font size for improved readability

package-lock.json, package.json, src/app/(auth)/forgot-password/components/forgot-password-form.tsx, src/app/(auth)/forgot-password/page.tsx, src/app/(auth)/layout.tsx, src/app/(auth)/reset-password/components/reset-password-form.tsx, src/app/(auth)/reset-password/page.tsx, src/app/(auth)/sign-in/page.tsx, src/app/(auth)/sign-up/page.tsx, src/app/layout.tsx, src/components/layout/app-sidebar.tsx, src/components/layout/data/sidebar-data.ts, src/components/layout/footer.tsx, src/components/layout/nav-group.tsx
This introduces the NextTopLoader component to enhance the loading experience in the application.
- Updated package.json and package-lock.json to include nextjs-toploader dependency.
- Modified layout.tsx to integrate NextTopLoader within the ThemeProvider.
Closes: #
=> Add bar loader and fix sidebar

prisma/migrations/20250501192718_add_field_isbanned_and_reason_to_member/migration.sql, prisma/schema.prisma, src/app/api/members/[id]/ban/route.ts, src/app/api/members/[id]/route.ts, src/app/api/members/[id]/unban/route.ts, src/app/api/members/route.ts, src/lib/services/member.service.ts, src/lib/services/transaction.service.ts, tailwind.config.ts
- Implemented POST endpoint to ban a member with a reason.
- Implemented POST endpoint to unban a member.
- Enhanced member search functionality to filter by tier.
- Added isBanned and banReason fields to the Member model.
Closes: #
=> feat(members): add ban and unban functionality for members

.github/workflows/docker-build.yml
=> fix(docker): update image tag for Docker build and push

src/app/(app)/dashboard/components/_parts/chart-sales-trend.tsx
=> fix(chart): add type assertions for sales data in SalesTrend component

src/lib/services/dashboard.service.ts
=> refactor(dashboard): enhance type definitions for sales mapping

src/lib/services/dashboard.service.ts
- Added 'day' property to SalesDataItem interface.
- Specified type for 'sales' variable in transactions mapping.
- Added type assertion for groupedData in reduce function.
Closes: #
=> fix(dashboard): correct SalesDataItem interface and improve type safety

.eslintrc.json, next.config.ts, package-lock.json, package.json
=> chore: add eslint and eslint-config-next for improved code quality

.eslintrc.json, package-lock.json, package.json
=> chore: update ESLint configuration and add TypeScript ESLint plugins

src/lib/services/dashboard.service.ts
=> fix(dashboard): improve type safety for payment method results

Dockerfile, src/lib/services/dashboard.service.ts, tsconfig.json
fix(dashboard): improve type safety for batch group in sales statistics
Closes: #
=> fix(docker): update Node.js base image to version 22-alpine

Dockerfile, src/lib/services/discount.service.ts
=> refactor(discount): clean up parameter formatting and type annotations

.gitignore, src/middleware.ts
This refactor updates the session fetching logic to use the appropriate base URL based on the environment. It also enhances error handling by logging session fetch errors and ensuring users are redirected to sign-in for protected routes if session verification fails.
Closes: #
=> refactor(middleware): improve session handling and error management

src/app/(auth)/sign-in/components/user-auth-form.tsx
This change introduces a delay before navigating to the home page to ensure the success toast is displayed and the session is properly set. It also adds a fallback mechanism for navigation in case the Next.js router fails.
Closes: #
=> fix(auth): improve navigation after successful login

package-lock.json, package.json, src/app/(app)/users/_components/user-sessions-dialog.tsx, src/app/(auth)/sign-in/components/actions.ts, src/app/(auth)/sign-in/components/user-auth-form.tsx
- Added headers to sign-in requests for better session management.
- Introduced a delay after sign-in to ensure session is properly set.
- Enhanced redirect strategy for post-login navigation.
- Improved user agent parsing in UserSessionsDialog for better device identification.
Closes: #
=> fix(auth): update authentication methods to include headers and improve session handling

src/app/(app)/users/_components/user-form-dialog.tsx, src/app/(app)/users/_components/user-table.tsx, src/app/(app)/users/action.ts, src/lib/types/user.ts
- Changed role property in User interface to UserRole type.
- Updated role handling in UserTable component to use UserRole.
- Adjusted role parameter types in user-related actions for consistency.
Closes: #
=> refactor(user): update user role handling to use UserRole type for better type safety

src/app/(auth)/sign-in/components/action.ts, src/app/(auth)/sign-in/components/user-auth-form.tsx, src/lib/auth.ts
=> fix(auth): fallback sign in

package-lock.json, src/app/(app)/dashboard/actions.ts, src/app/(app)/dashboard/components/_parts/low-product-stock.tsx, src/app/(app)/dashboard/components/_parts/top-discount.tsx, src/app/(app)/dashboard/components/_parts/top-member.tsx, src/app/(app)/dashboard/components/_parts/top-selling-product.tsx, src/app/(app)/dashboard/page.tsx, src/app/(app)/inventory/_components/stock-out-table.tsx, src/lib/services/dashboard.service.ts, src/lib/services/product.dashboard.service.ts, src/lib/services/stock-movement.service.ts, src/lib/types/dashboard.ts
=> Dashboard jun

src/app/(app)/dashboard/components/_parts/chart-payment-method.tsx, src/app/(app)/dashboard/components/_parts/chart-sales-category.tsx, src/app/(app)/dashboard/components/_parts/chart-sales-trend.tsx, src/app/(app)/dashboard/components/_parts/low-product-stock.tsx, src/app/(app)/dashboard/components/_parts/top-discount.tsx, src/app/(app)/dashboard/components/_parts/top-member.tsx, src/app/(app)/dashboard/components/_parts/top-selling-product.tsx, src/app/(app)/dashboard/components/overview-sales.tsx, src/app/(app)/dashboard/page.tsx, src/i18n/en/dashboard.json, src/i18n/id/dashboard.json, src/i18n/request.ts
Penambahan translate indonesia dan english pada halaman dashboard
=> feat: add internationalization support for dashboard components

src/app/api/members/calculatePoints/route.ts
=> fix(api): change GET to POST for calculatePoints endpoint

src/app/(app)/dashboard/page.tsx
=> refactor: remove debug logging from Dashboard component

src/lib/services/transaction.service.ts, src/lib/services/transaction/data.ts
This introduces a new method to generate transaction IDs in the format YYYYMMDD0001, ensuring uniqueness by counting existing transactions for the day. Additionally, helper methods for date formatting and range querying are added.
Closes: #
=> fit(transaction): implement unique transaction ID generation with daily counter

src/app/(app)/transactions/_components/transaction-generate-pdf.tsx, src/app/(app)/transactions/_components/transaction-pricing-summary.tsx, src/i18n/en/transaction.json, src/i18n/id/transaction.json, src/lib/services/transaction/get-transaction.ts, src/lib/services/transaction/types.ts, src/middleware.ts
- Introduced global discount handling in transaction pricing summary.
- Updated translation files to include global discount labels.
- Refactored discount calculation logic to accommodate global discounts.
Closes: #
=> fix(transaction): add global discount support in transaction summary

src/app/(app)/dashboard/hooks/useMetricPerformance.ts, src/app/(app)/discounts/_components/discount-table.tsx, src/app/(app)/transactions/_components/transaction-pricing-summary.tsx, src/lib/services/dashboard.service.ts
=> Refactor service transaction

src/app/(app)/members/[id]/page.tsx
=> fix(member): update breadcrumb logic to use context for member name
